#!/bin/bash
###########################################################
##################### INITIALIZATION ######################
###########################################################

set $mod Mod4
floating_modifier $mod

# Font for window titles
font pango:DejaVu Sans Mono for Powerline 15

# Setup displays
exec --no-startup-id ~/.screenlayout/monitor.sh

# Start Network Manager
exec --no-startup-id nm-applet

# Start the compositor
exec --no-startup-id picom -b

# Star the authentication agent
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Activate num lock
exec --no-startup-id numlockx on

# Start .desktop files
exec --no-startup-id dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# set wallpaper
exec --no-startup-id nitrogen --restore

#set powersavings for display:
exec --no-startup-id xset s 480 dpms 600 600 600

# Desktop notifications
exec --no-startup-id dbus-launch dunst --config ~/.config/dunst/dunstrc

# Polybar
exec_always --no-startup-id ~/.config/polybar/launch.sh


###########################################################
###################### APPLICATIONS #######################
###########################################################

# Start a terminal
bindsym $mod+Return exec alacritty
bindsym $mod+Shift+Return exec alacritty --working-directory `xcwd`

# Start Browser
bindsym Mod1+b exec microsoft-edge-beta
bindsym Ctrl+Mod1+b exec "killall microsoft-edge-beta && microsoft-edge-beta"

# Start VSCode
bindsym Mod1+v exec code

# Screenshots
bindsym Print exec gnome-screenshot -i

# Color Picker
bindsym $mod+Mod1+c  exec "~/.config/i3/scripts/colorpicker --one-shot --short --preview | xsel -b"

# Application Menu
bindsym $mod+x exec rofi -modi drun -show drun -display-drun "Apps : " -line-padding 4 \
                -columns 2 -padding 50 -hide-scrollbar \
                -show-icons -drun-icon-theme "Arc-X-D" -font "Noto Sans Regular 11"

# Window Menu
bindsym Mod1+Tab exec "rofi -show window -mode window -window-thumbnail -theme /home/jaren/.config/rofi/themes/windows.rasi"

# Power Menu
bindsym Control+Mod1+p exec ~/.config/rofi/powermenu/powermenu.sh

# Project Menu
bindsym $mod+Shift+a exec ~/.local/bin/venture

###########################################################
###################### APPEARANCE #########################
###########################################################

#border indicator on windows:
new_window pixel 1


# Define colors variables:
set $darkbluetrans	#08052be6
set $darkblue		#08052b
set $lightblue		#5294e2
set $urgentred		#e53935
set $white		#ffffff
set $black		#000000
set $purple		#e345ff
set $darkgrey		#383c4a
set $grey		#b0b5bd
set $mediumgrey		#8b8b8b
set $yellowbrown	#e1b700

# define colors for windows:
#class                      border         bground        text		indicator	child_border
client.focused              #6272A4        #6272A4        #F8F8F2   #6272A4     #6272A4
client.focused_inactive     #44475A        #44475A        #F8F8F2   #44475A     #44475A
client.unfocused            #282A36        #282A36        #BFBFBF   #282A36     #282A36
client.urgent               #44475A        #FF5555        #F8F8F2   #FF5555     #FF5555
client.placeholder          #282A36        #282A36        #F8F8F2   #282A36     #282A36


###########################################################
####################### I3 GAPS ###########################
###########################################################


# Set inner/outer gaps
gaps inner 18
gaps outer 0

hide_edge_borders smart_no_gaps

###########################################################
##################### KEYBINDINGS #########################
###########################################################

# kill focused window
bindsym $mod+q kill

# Lock the system
# lock with a picture:
#bindsym $mod+l exec i3lock -i  ~/.config/i3/i3-lock-screen.png -p default|win -t
# lock by blurring the screen:
bindsym $mod+l exec ~/.config/i3/scripts/blur-lock.sh

# reload the configuration file
bindsym $mod+Shift+c reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

# Change focus
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# Move Windows
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# open new empty workspace
bindsym $mod+Shift+n exec ~/.config/i3/scripts/empty_workspace.sh

# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

###########################################################
###################### WORKSAPCES #########################
###########################################################

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

set $wsb "brower"
set $wsp "programming"
set $wst "terminal"
set $wsm "music"
set $wsd "discord"

set $monitor_left DP-2
set $monitor_right DP-0

workspace $wst output $monitor_left
workspace $wsp output $monitor_left
workspace $wsb output $monitor_right
workspace $wsm output $monitor_right
workspace $wsd output $monitor_right

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

bindsym $mod+b workspace $wsb
bindsym $mod+p workspace $wsp
bindsym $mod+t workspace $wst
bindsym $mod+m workspace $wsm
bindsym $mod+d workspace $wsd

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

bindsym $mod+Shift+b move container to workspace $wsb
bindsym $mod+Shift+p move container to workspace $wsp
bindsym $mod+Shift+t move container to workspace $wst
bindsym $mod+Shift+m move container to workspace $wsm
bindsym $mod+Shift+d move container to workspace $wsd

# Moves entire workspace to the next monitor
bindsym $mod+Control+Right move workspace to output right
bindsym $mod+Control+Left move workspace to output left

# bind program to workspace and focus to them on startup:
assign [class="Alacritty"] $wst
assign [class="Microsoft-edge-beta"] $wsb
assign [class="Code"] $wsp
assign [class="discord"] $wsd
for_window [class="Spotify"] move to workspace $wsm


# automatic set focus new window if it opens on another workspace then the current:
for_window [class="Alacritty"] focus
for_window [class="Microsoft-edge-beta"] focus
for_window [class="Code"] focus
for_window [class="discord"] focus
for_window [class="Spotify"] focus



###########################################################
#################### MISCELLANEOUS ########################
###########################################################


# resize window (you can also use the mouse for that):
mode "resize" {
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym ntilde resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
	bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
	bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"


#set floating (nontiling) for special apps
for_window [class="Pavucontrol" instance="pavucontrol"] floating enable
for_window [class="Gnome-screenshot"] floating enable
for_window [class="Gpick"] floating enable
